### ISSUE TITLE
Allow Pinning of Project

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#202]
User had suggestions to let you share projects across organization (see ticket). I think this could be at least partially addressed by letting people "pin" any project to add it to their sidebar, even if they don't have explicit permissions to it. Need to think through a bit more.

**Comment by mitchelljkotler** [comment]
Adding to this after the sidebar upgrade:  Just being able to pin your own projects to choose which ones are in the sidebar, similar to how add-ons work seems like it would be an improvement.  There can be another way to view all of your projects, and just keep your active ones in the sidebar.
