### ISSUE TITLE
Upgrade StorybookJS

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#242]
Latest version is v7.3.0. Last time I tried it broke a couple stories, so this should happen outside of feature development.

**Comment by allanlasser** [comment]
I did a little testing on this and it seems like there's some kind of parsing issue with `addon-storybook-csf` — so far I've been unable to reproduce in a clean test environment, which leads me to believe there's some kind of conflict with our Svelte processing or Webpack configs.

Will continue investigating when I have more time.
