### ISSUE TITLE
Allow projects to be marked as discoverable

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-frontend#268]
# What is the problem we are trying to solve?

Currently, other user’s projects are not searchable via project: in the search bar in an easy way. We should add some kind of way for an admin of a project to mark a project as discoverable/indexable and to have the ability for that project to appear in the autocomplete results. This will make it easier for users to find projects from other users that concern similar subject material. 

# How wide spread is this issue?

It would affect all DocumentCloud users. 

# How can we solve this issue?

We add some kind of toggle to mark projects as publicly discoverable, and then include those entries in the autocomplete system.

**Comment by duckduckgrayduck** [comment]
This is another feature request that will be discussed with users as we talk about the future of projects.

**Comment by eyeseast** [comment]
We might have decided not to do this. If so, we can close.

**Comment by amandabee** [comment]
We don't see a reason not to move forward with this. Because there's no urgency and the Election Hub is launching, we're going to revisit this in the July 1 project planning and plan to move on it after July 4.

**Comment by duckduckgrayduck** [comment]
@eyeseast @allanlasser Amanda let us know on Slack we can move forward with this
