### ISSUE TITLE
Use flatpage content for DocCloud homepage

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#270]
Depends on https://github.com/MuckRock/documentcloud/issues/165

Someone also needs to create the content.

**Comment by amandabee** [comment]
https://www.notion.so/muckrock/Copy-Updates-03c0ba7f882242e5934a5149fe3f5758 has the content;

@acnatta will move the content into a flat page and @eyeseast will work on using the flatpage.

**Comment by eyeseast** [comment]
Closed in #275
