### ISSUE TITLE
Hide the option for de-indexing when user selects to upload the document privately. 

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-frontend#278]
Had a user report that it was confusing that when they selected "private" under the change access menu, that the "hide from search engines and DC search" check box still appears.

**Comment by eyeseast** [comment]
![Image](https://github.com/MuckRock/documentcloud-frontend/assets/25778/322a068d-c60a-4e17-acd5-afb8f9c021a6)

**Comment by eyeseast** [comment]
We can probably solve this need with better language about what private access vs de-indexing means.
