### ISSUE TITLE
Add a separate instructions field for add-ons

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#314]
Lots of add-ons have instructions in the description field. Let's separate those out and only show instructions in the dispatch view.

**Comment by eyeseast** [comment]
First step is updating configs in existing add-ons to add an `instructions` field. Assigning that to @duckduckgrayduck.

**Comment by duckduckgrayduck** [comment]
This is done, minus Add-Ons that have fallen out of maintenance from other authors. @eyeseast

**Comment by eyeseast** [comment]
Reassigned this to me, so I can get it implemented on the add-on dispatch, probably next week.

**Comment by eyeseast** [comment]
@mitchelljkotler Is the `instructions` field getting processed as Markdown on the backend?

**Comment by eyeseast** [comment]
Done via #374
