### ISSUE TITLE
Add-On list should default to featured, not all

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#315]
We have lots of add-ons, so let's show the featured ones first. They're the easiest to jump into.

**Comment by duckduckgrayduck** [comment]
addOnsMenu 
browseAll
./src/pages/app/menus/AddonsMenu.svelte shows the browseAll, but I'm not sure how to apply the filter right off the bat

**Comment by eyeseast** [comment]
Here https://github.com/MuckRock/documentcloud-frontend/blob/master/src/addons/browser/Filters.svelte#L3
