### ISSUE TITLE
Kill the Twitter links

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#316]
The site has a new logo. It sort of has a new name. Do we even want to have it in our share options anymore?

**Comment by morisy** [comment]
Briefly came up in another conversation with @amandabee — I'm in favor of ditching the button and either expanding the others or just ditching the share bar in general. If you have some ideas or seen something you really like elsewhere, let's go with that — my default would just be ditch the share button and if we want to use that real estate for something down the line, we can go for it then.

<img width="411" alt="Screenshot 2024-02-08 at 9 09 47 PM" src="https://github.com/MuckRock/documentcloud-frontend/assets/136939/0251be6c-5ede-45fc-9b2a-8c6b8864d721">

**Comment by amandabee** [comment]
I'm in favor of ditching the whole share bar.

**Comment by eyeseast** [comment]
On the DocumentCloud side, the share buttons only show up when you have the share dialog open, so most people don't even see them. Twitter is the only site we have specifically, too. And it ends up adding a whole row of space. All this makes me want to just take it out. 

![Image](https://github.com/MuckRock/documentcloud-frontend/assets/25778/02aa16da-4e7f-49b7-b119-0eb9e2443425)

**Comment by eyeseast** [comment]
It has been decided: Kill the twitter button (because no one clicks on share buttons anyway).
