### ISSUE TITLE
Viewer shows a 404 when document is reprocessing

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#317]
The document is inaccessible, and API is probably returning a 404, but that's not the right message to send to users.

To reproduce: Open a document, redact it and save redactions. It'll show a 404 Not Found message until it finishes reprocessing.

**Comment by mitchelljkotler** [comment]
I just encountered this - I don't think the API is returning a 404 - this used to work properly, where the frontend would show a "Processing, please wait" message and would poll and refresh when it was finished processing.  I think it might be a regression in the frontend.
