### ISSUE TITLE
Large document fails to show plaintext view 

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-frontend#320]
https://www.documentcloud.org/documents/24040185

You will have to access as the user to see the document failing to load the plaintext view. 

Shown here: 
![Bug on Plaintext](https://github.com/MuckRock/documentcloud-frontend/assets/102841251/d2fd870e-d565-4322-8eb9-0ea7f795fcf8)

**Comment by duckduckgrayduck** [comment]
+user:barry-friedman-11401

**Comment by eyeseast** [comment]
This should be fixed now, after #322
