### ISSUE TITLE
Add an action alongside to the sidebar's "Add-Ons" header

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#341]
While reviewing the UI with Mitch, he noted that it's not obvious that clicking the "Add-Ons" header in the sidebar will open the browser drawer. To parallel the Projects section with the "+ Add Project" action button, we can add a "Browse" button that makes it clearer how to open the drawer.

I intend to address this feedback with a small PR soon.

**Comment by eyeseast** [comment]
Closed via #399
