### ISSUE TITLE
DocumentCloud viewer doesn't supported Adobe Acrobat highlights

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-frontend#409]
A user uploads a document with an annotation created in Adobe Acrobat

The document in our viewer doesn't render the highlights

See an example of a highlight here:
![Note](https://github.com/MuckRock/documentcloud-frontend/assets/102841251/41a86295-7f52-40a3-b50e-465294d83e42)

**Comment by mitchelljkotler** [comment]
PDFs are rendered using PDFium, so if it does not support these, we do not support them
