### ISSUE TITLE
Embeds hitting /api/users/me endpoint

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud-frontend#411]
Moesiff alerted me to an uptick in traffic this past week.  I dove in to the graph a little and noticed a large uptick in requests to /api/users/me which should not be happening:

https://www.moesif.com/wrap/app/88:1445-198:915/search/time/dates/-4w?evt_ts[metrics][0][metricName]=sum%28events%29&evt_ts[interval]=1d&evt_ts[groups][0][field]=request.route.raw&evt_ts[groups][0][func]=terms&evt_ts[groups][0][by]=metric

**Comment by allanlasser** [comment]
I'm having trouble viewing this, could you make sure I have access through my GitHub account or my `lasser.design` email?

**Comment by mitchelljkotler** [comment]
Traffic is back to normal
