### ISSUE TITLE
Decide if routes should end in a trailing slash

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#418]
Both of these URLs work without a redirect:

- https://www.documentcloud.org/help
- https://www.documentcloud.org/help/

We should settle on a style and redirect as appropriate.

**Comment by mitchelljkotler** [comment]
I would prefer to use the trailing slash to be consistent with Django

**Comment by eyeseast** [comment]
This is now set on the `sveltekit` branch. Not going to bother with the current branch.
