### ISSUE TITLE
Replace "fullscreen" icon in embed footer with DocumentCloud logo

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#449]
When I used the "fullscreen" action in the viewer embed, I found myself looking for a way to exit the fullscreen mode. Not having any button in the UI confused me until I realized that the "fullscreen" action opens a new tab, not a fullscreen element of the page I'm on.

I can imagine a few possible solutions:

1. Change the link from a 'fullscreen' icon to a 'new tab' icon.
2. A button in the full-screen embed UI for 'exit fullscreen' — the visibility of which could be controlled by a query arg or a cookie — that closes the tab.
3. Supporting two viewer embed actions: Open in new tab _and_ View fullscreen. Right now the two are implicitly linked and could be explicitly separated into two controls.

**Comment by eyeseast** [comment]
Maybe something akin to youtube's embeds: `View on DocumentCloud` with the logo.

**Comment by allanlasser** [comment]
I think YouTube is a good model to follow.
