### ISSUE TITLE
Consolidate mocks and fixtures at project route

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#451]
We have mocks and fixtures scattered throughout the codebase, used by both tests and Storybook files. Let's put these all in one place and be consistent about it.

**Comment by eyeseast** [comment]
Vitest guide to mocking: https://vitest.dev/guide/mocking.html

MSW: https://mswjs.io/docs/

**Comment by allanlasser** [comment]
I have a pretty clear vision on how to do this with compatability for the `sveltekit` branch, so I'm just going to knock it out.
