### ISSUE TITLE
Upload view

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#464]
In SvelteKit, this can be its own route, rather than a modal.

This needs to handle the multi-step upload process using the API: https://www.documentcloud.org/help/api#uploading-a-document

**Comment by eyeseast** [comment]
Right now, we don't have a built-in way to upload documents via URL. There's an add-on that does it, but nothing native. Might be nice to have that option.

**Comment by eyeseast** [comment]
For the three-step upload, I think I want three methods that work together:

- `create` makes a new document and returns a pre-signed URL
- `upload` puts the actual file in cloud storage using the pre-signed URL
- `process` starts processing a document, or reprocesses

These need to handle one or more documents at a time.

**Comment by eyeseast** [comment]
Here's a pattern for testing file uploads https://testing-library.com/docs/svelte-testing-library/faq/#how-do-i-test-file-upload

**Comment by eyeseast** [comment]
Ultimately, we probably need a Playwright test that actually uploads a file in staging, waits for it to process and then deletes it at the end of the test.

**Comment by eyeseast** [comment]
@allanlasser suggests consolidating form components in `lib/forms` and I agree. Getting those components defined on their own, outside of `+page.svelte` files, will make testing easier.

**Comment by duckduckgrayduck** [comment]
Couple comments:

- This looks good. My only comment would be to make this entire area a drop zone for documents, or move the upload section above 





![Image](https://github.com/MuckRock/documentcloud-frontend/assets/102841251/8eb10c86-598e-437d-b444-57f739c05a21)

**Comment by eyeseast** [comment]
I think that'll happen. I'll make an issue for it.
