### ISSUE TITLE
Decide initial loading flow

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#485]
On the current site, loading `www.documentcloud.org` will (eventually) redirect a logged-in user to the manager with their own documents as the default search. Anonymous users get redirected to the home page.

Do we want to keep this flow, or do something different?

**Comment by allanlasser** [comment]
https://stackoverflow.com/questions/71360354/redirecting-from-exported-handle-hook-in-sveltekit

**Comment by eyeseast** [comment]
Decision: Match current experience, and add in a link to "all of your documents" in the sidebar.

Eventually: Kill the `/home/` page and load the search view.
