### ISSUE TITLE
Search highlights

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#501]
Current version: https://www.documentcloud.org/app?q=boston

API: https://api.www.documentcloud.org/api/documents/search/?q=boston&hl=true&expand=user,organization

Highlights are both pages and notes.

**Comment by eyeseast** [comment]
Solr is already marking text for us as `<em>` tags: https://github.com/MuckRock/documentcloud/blob/master/config/solr/solrconfig.xml#L1331-L1339

Might be nice to switch those to `<mark>` since that's more semantic.

**Comment by eyeseast** [comment]
A big chunk of [`src/structure/document.js`](https://github.com/MuckRock/documentcloud-frontend/blob/master/src/structure/document.js) is concerned with transforming highlights. I wonder if we actually need all of that or if we can rely on what Solr gives us.

**Comment by eyeseast** [comment]
We currently show page thumbnails (smaller than main document thumbnails) for each text highlight, and we link to the relevant page:

<img width="1166" alt="Screenshot 2024-04-19 at 10 27 17 AM" src="https://github.com/MuckRock/documentcloud-frontend/assets/25778/70c8e9c9-82b9-4b62-b83e-b45758e483cd">

For note highlights, we link to the relevant note:

<img width="982" alt="Screenshot 2024-04-19 at 10 27 31 AM" src="https://github.com/MuckRock/documentcloud-frontend/assets/25778/998a3fed-9aac-4430-8ee6-6004188b160d">

**Comment by eyeseast** [comment]
Need to represent the in-document search results, too:

<img width="1512" alt="Screenshot 2024-05-14 at 10 17 49 AM" src="https://github.com/MuckRock/documentcloud-frontend/assets/25778/92045127-41ab-4776-85fc-279c8257afd2">

<img width="525" alt="Screenshot 2024-05-14 at 10 18 43 AM" src="https://github.com/MuckRock/documentcloud-frontend/assets/25778/84028bda-0f7f-4f25-90f1-7e3cc7b9d2cc">

API response: https://api.www.documentcloud.org/api/documents/24438447/search/?q=%22Los%20Angeles%22

**Comment by allanlasser** [comment]
![screenshot-grammar@2x](https://github.com/MuckRock/documentcloud-frontend/assets/6089482/f670f404-55b8-4748-91c5-dd976c0a8628)

Just saw this screenshot and really liked its approach to providing inline highlights as a list of results.

**Comment by allanlasser** [comment]
Questions from milestones planning document:

- Do we need a dedicated search results view?
- If so, where does clicking on a search result take you?
- How do we represent search results in the document and text views?
- Do we need to hit the server?
- Can PDF.js handle search for us?
- How do we match search results to text in the document?

**Comment by eyeseast** [comment]
> Questions from milestones planning document:
> 
> * Do we need a dedicated search results view?
> * If so, where does clicking on a search result take you?
> * How do we represent search results in the document and text views?
> * Do we need to hit the server?
> * Can PDF.js handle search for us?
> * How do we match search results to text in the document?

These were all about in-document search, which we ended up handling client-side. I might do another iteration on that at some point, but for now, I think the only need is for highlights in `/documents/`.
