### ISSUE TITLE
Support drag-n-drop upload in search view

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#518]
The current manager interface allows a user to start and upload by dragging a file into the search area. We should continue to let people do some version of this.

**Comment by allanlasser** [comment]
With the upload form on its own route, is there a way to pre-load it with files? The files variable is already exported/settable for testing purposes. Ideally, we could wrap the ResultsList in a Dropzone that routes to the upload form with the dropped files.

**Comment by eyeseast** [comment]
> With the upload form on its own route, is there a way to pre-load it with files? The files variable is already exported/settable for testing purposes. Ideally, we could wrap the ResultsList in a Dropzone that routes to the upload form with the dropped files.

Good question. I bet there is a way, so long as we're client-side routing.
