### ISSUE TITLE
Add Lighthouse to CI project

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#527]
Two ways to do it:

- [Netlify plugin](https://github.com/netlify/netlify-plugin-lighthouse)
- [Github Actions](https://github.com/marketplace/actions/lighthouse-ci-action)

**Comment by eyeseast** [comment]
Accessibility scoring: https://developer.chrome.com/docs/lighthouse/accessibility/scoring

**Comment by allanlasser** [comment]
I think these two actions are winners:

- https://github.com/JakePartusch/wait-for-netlify-action
- https://www.foo.software/docs/lighthouse-check-github-action/intro
