### ISSUE TITLE
Viewer pagination

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#533]
This applies to the `document` and `text` modes:

- I want to be able to link to a specific page.
- I want to know what page I'm on as I scroll through a long document.
- I want to go to a specific page, using the paginator control

**Comment by allanlasser** [comment]
From #532:

> When trying to load a specific page by target (i.e. refreshing a URL ending in #p10), the element is not brought into view. I believe the issue is that the element being targeted is not present when the page loads—it's loaded in after. There's a small flash where the mode is "Document" and the view is empty, before switching to "Text" and displaying the text pages. Either the page should be scrolled into view after streaming finishes ([example](https://svelte.dev/repl/e073dc93fb3347848062a531271e497f?version=3.24.0)) or we should change how we're server-rendering the page.
