### ISSUE TITLE
Documents should be viewable before processing finishes

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#543]
With PDF.js, we'll be able to view a document as soon as it's uploaded. This raises some questions:

- I'm not sure if that has privacy implications (since the original file is in private storage until it's done processing and marked public). 
- I also don't know what other parts of the UI will depend on full processing.
- If there's an error in processing, we might need to nudge people to reprocess.

**Comment by eyeseast** [comment]
Assets we might not have when the document is viewable:

- images
- page spec

What else?

We can actually generate thumbnails and page sizes directly from the PDF if needed.

**Comment by allanlasser** [comment]
My pitch would be a minimally-useful viewer while the document is in a processing state. Disabling options and links, such as:
- thumbnails and notes views
- annotations

An enhancement would be using native browser notifications to let people know when a document or upload finishes processing.

**Comment by eyeseast** [comment]
Thinking about this more, the parts we're not likely to have are mostly on S3: page images, text, text positions. I agree on making the document read-only until it's done processing. We can probably render notes if a document has them and is reprocessing.

I guess one question is whether there will be a point where we don't have a PDF file, and what to show in that state.

**Comment by allanlasser** [comment]
I'm going to pick this thread back up to propose:

- Update `PDF` component to handle cases where:
  - PDF is missing and display an empty message.
  - Text is missing and don't render the TextLayer.

**Comment by eyeseast** [comment]
I think there's also an issue related to #576. I've had some large documents load and then unload because we invalidated the data on the page.
