### ISSUE TITLE
Show document loading progress

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#547]
If I have a giant document, it might take enough time to load that we should show a progress indicator of some kind (a bar, a percent, a spinner, etc). We have the data already.

**Comment by allanlasser** [comment]
@eyeseast Is this still necessary after #568?

**Comment by eyeseast** [comment]
We probably want to finalize the messaging, but I don't think we need a dedicated view now. I'll take the design tag off.

**Comment by allanlasser** [comment]
@eyeseast Can you point to where the loading data is provided? I can probably tackle this in a slim UI PR.

**Comment by eyeseast** [comment]
https://github.com/MuckRock/documentcloud-frontend/blob/sveltekit/src/lib/components/documents/PDF.svelte#L52-L55

The loading task emits a [progress event](https://github.com/MuckRock/documentcloud-frontend/blob/sveltekit/src/lib/components/documents/PDF.svelte#L64-L66) with `total` and `loaded` values. I'm storing that object but not doing anything with it yet.
