### ISSUE TITLE
Render notes in document view

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#549]
There are two states: Focused and not.

Focused:

<img width="916" alt="Screenshot 2024-05-17 at 7 56 34 PM" src="https://github.com/MuckRock/documentcloud-frontend/assets/25778/bfcad9cd-7f54-4f78-8b82-d681d05df765">

Not focused (default):

<img width="886" alt="Screenshot 2024-05-17 at 7 56 42 PM" src="https://github.com/MuckRock/documentcloud-frontend/assets/25778/3e7f1cec-2efd-486c-b1e5-6899b2430076">

**Comment by eyeseast** [comment]
Here's the API response for a document with notes: https://api.www.documentcloud.org/api/documents/2622/?expand=~all

Type: https://github.com/MuckRock/documentcloud-frontend/blob/sveltekit/src/lib/api/types.d.ts#L140-L155

**Comment by allanlasser** [comment]
https://www.figma.com/design/KVRuo8Ss3TvzreCmT6HQke/DC-SvelteKit?m=dev&node-id=3069%3A715&t=a9T8I6EVWPEhY6AY-1

https://www.figma.com/design/KVRuo8Ss3TvzreCmT6HQke/DC-SvelteKit?m=dev&node-id=3069%3A1754&t=a9T8I6EVWPEhY6AY-1

https://www.figma.com/design/KVRuo8Ss3TvzreCmT6HQke/DC-SvelteKit?m=dev&node-id=3069%3A2143&t=a9T8I6EVWPEhY6AY-1
