### ISSUE TITLE
Annotate a document

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#561]
API docs: https://www.documentcloud.org/help/api#notes

Need a rendered PDF so we can draw a box on top of it. Probably also need a note form. This might also be a chance to extract a document excerpt component.

We may need some UI to add page-level notes.

**Comment by duckduckgrayduck** [comment]
Users have requested for annotation- and key/value pair adding and probably OCR edits to not break out of the viewer while making these edits. Currently, it blurs out the background while writing a note
