### ISSUE TITLE
Share dialog

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#563]
This is probably a modal that can be opened in the viewer or search view.

**Comment by allanlasser** [comment]
As a part of making pages easy to share, we should also make sure they have well-formed head tags for social.

Sharable routes:

- `documents/<id>`
- `projects/<id>`

Am I missing any obvious ones to start with?

Is creating embeds the same thing as sharing?

**Comment by eyeseast** [comment]
I think there's two ways to share:

- embed a document, project, page, note
- share a link to one of those

We can generate embed codes via our oembed endpoint: https://api.www.documentcloud.org/api/oembed/?url=https://www.documentcloud.org/documents/282753-lefler-thesis.html (or we can just construct iframes directly)
