### ISSUE TITLE
Help menu should link to donate page

### ISSUE THREAD

**Issue by amandabee** [MuckRock/documentcloud-frontend#567]
Text: Donate to support DocumentCloud
Link: goes to main donate page.

**Comment by duckduckgrayduck** [comment]
I need an icon to add this into the help menu. Not sure if this  is a @allanlasser or @eyeseast task

**Comment by duckduckgrayduck** [comment]
Yea, I think we need a new icon specifically for donation, since this will appear under the help dropdown menu. I didn't see an icon in there

**Comment by amandabee** [comment]
Looking at the Svelte Octicons any of these would work: * Gift (1st Choice)* Code of Conduct* Credit Card (2nd)* Sponsor Tiers* Trophy (3rd)I think Gift makes the most sense, but if you disagree, I don’t feel at all strongly. Sent from my iPadOn Jul 9, 2024, at 8:16 AM, Sanjin ***@***.***> wrote:﻿
Yea, I think we need a new icon specifically for donation, since this will appear under the help dropdown menu. I didn't see an icon in there

**Comment by duckduckgrayduck** [comment]
Woops, I was looking at the octicons already in our repo, not the ones you  linked, I agree that gift should work fine. I'll include it!

**Comment by duckduckgrayduck** [comment]
This was resolved in https://github.com/MuckRock/documentcloud-frontend/pull/587
