### ISSUE TITLE
500 error when viewing document page anonymously

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#569]
I've hit this a few times following links to the staging server. While signed out, document routes (`/document/[id]-[slug]`) report 500 errors.

When viewing a document without permission, it should return a 404 page that includes a link back to the manager and a button to sign in.

**Comment by eyeseast** [comment]
Can you post a URL where you're hitting this? There's something weird happening with staging that is causing an uptick in 500s.

**Comment by allanlasser** [comment]
Ah interesting. I was hitting it on https://deploy-preview-568.muckcloud.com/documents/20006371-smallsville/, but that's no longer the case.

**Comment by eyeseast** [comment]
Yeah, it was an issue with PDF.js using `Promise.withResolvers`, which is available in browsers but not in Node until 22, which it turns out we can't even get on yet. I'm not sure why it was being called server-side at all, but I added a polyfill, so that fixed this issue.
