### ISSUE TITLE
Snackbar component

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#595]
A [snackbar](https://m2.material.io/components/snackbars) is useful UI pattern for providing success or failure feedback to users after they take an action in the application.

Building upon #578, we can use a `Portal` to insert snackbars into the application in a scalable way. Snackbars should have a "timeout" property that dismisses the component after the timeout expires (a timeout of `0` will keep the snackbar mounted until manually dismissed).

We'll also need a mechanism to dispatch snackbars from other components or application functions. An interface for this snackbar dispatch will be necessary.

**Comment by eyeseast** [comment]
It's possible this can replace the current site's [`Toast`](https://github.com/MuckRock/documentcloud-frontend/blob/master/src/common/Toast.svelte) component.

**Comment by allanlasser** [comment]
Try adding messages to a SnackbarStore to start off, see how that goes.

**Comment by allanlasser** [comment]
> It's possible this can replace the current site's [`Toast`](https://github.com/MuckRock/documentcloud-frontend/blob/master/src/common/Toast.svelte) component.

Yeah, Toast gets us very far on this.
