### ISSUE TITLE
Point `next.documentcloud.org` to `sveltekit` branch deployment

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#597]
We are planning to provide a preview deployment for SRCCON. We're already pointing `sveltekit.muckcloud.com` to a deployment of the `sveltekit` branch.

We should also point `next.documentcloud.org` to this branch.

In doing so, we'll need to make sure:
- [ ] squarelet's production config allows access from this subdomain
- [ ] the connection to production API and S3 works as expected

These could be created as new issues if needed.

**Comment by eyeseast** [comment]
Investigating how to do this:

- On Netlify, we can set environment variables based on branch name, so `sveltekit` could set `NODE_ENV=production`. 
- We could also create a `preview` branch or something similar, if we want another level of separation. I'm not sure we need to do this, but we could.
- We need to add a subdomain record on CloudFlare that proxies `www.next.documentcloud.org` to `sveltekit.muckcloud.org`.
- We may want some kind of flag on the site that says we're in preview mode, and use that to conditionally show whatever warnings and banners we have so people know this is still the test version.

**Comment by eyeseast** [comment]
I also need to either add a redirect from `/app` to `/` or fix https://github.com/MuckRock/documentcloud/issues/234

**Comment by eyeseast** [comment]
Hitting issues with Netlify and Cloudflare, similar to what happened when we configured deploy previews. I wonder if it's worth actually creating a separate Netlify site for `next.documentcloud.org`, like we used to do with staging. That site would exclusively build from the `sveltekit` branch and might solve the DNS issues.

**Comment by allanlasser** [comment]
> I also need to either add a redirect from `/app` to `/` or fix [MuckRock/documentcloud#234](https://github.com/MuckRock/documentcloud/issues/234)

I think that an in-app redirect makes the most sense for now. We should avoid messing with the backend if possible.
