### ISSUE TITLE
Guided tour for first-time users

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#598]
As part of preparing a public preview, we should add a guided tour for first-time users. We can consider the [Driver.js](https://driverjs.com/docs/basic-usage) library. It provides everything we need to get started.

If created manually, tour elements can mount to different UI elements by ID using our `Portal` component.

- What is our heuristic for a first-time user? Is it by browser and tracked by cookie/localStorage, by user and tracked by a database flag, or some other qualification?
- Will we want to create guided tours dynamically, or have them hard-coded?

**Comment by allanlasser** [comment]
To move this forward, let's proceed without relying on any backend changes.

- For now, we can use a value in Local Storage to indicate whether a user is new. Long term and before public launch, we should store this value on the user's account.
- For now, we can hard-code our guided tours. Once we understand the configuration better, we can create a new model a la flatpages that can be used for content management of user onboarding.

**Comment by eyeseast** [comment]
This could also just be a video we link from the top, if we need a no-code solution.

**Comment by allanlasser** [comment]
@duckduckgrayduck is going to help with drafting a script for our guided tour.

**Comment by allanlasser** [comment]
This Notion document contains walkthrough copy and steps drafted by @duckduckgrayduck: https://www.notion.so/muckrock/DocumentCloud-Walkthrough-111f8892696380ed8ed7f3a0d4373d35?pvs=4
