### ISSUE TITLE
Organization menu

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#602]
When selecting the organization in the global navigation, it should present a menu that lists premium account balance, org members, and allows the user to change orgs. This should be relatively unchanged port of the existing OrgMenu component.

**Comment by eyeseast** [comment]
We need to load a user's list of organizations in the root `+layout.ts`. It looks like we can't do that as an expandable property, so we'll have to do a second API call with a list of organizations.

**Comment by eyeseast** [comment]
Capturing current state here:

![Screenshot 2024-07-24 at 4 55 10 PM](https://github.com/user-attachments/assets/b4f99167-9caf-4e5c-9d9d-0e9fac762ca2)

We need:

- a list of organizations I belong to
- my active organization
- users in my active organization
- org credit allowance

I think that's three requests, which we can make in parallel but after we know the current user.

**Comment by allanlasser** [comment]
I'll just add that we could stream in the list of org users, since that data isn't necessary until the menu is opened.

**Comment by eyeseast** [comment]
> I'll just add that we could stream in the list of org users, since that data isn't necessary until the menu is opened.

I think we can stream all three of those requests. The only thing we need to show the menu when it's closed is the current user and active organization, and we can get those in one request.

**Comment by eyeseast** [comment]
Lumping this menu in, because this is what we show users on the free plan.

![Screenshot 2024-07-25 at 11 43 13 AM](https://github.com/user-attachments/assets/cd642e6c-afe0-4074-97df-22833c4362a5)
