### ISSUE TITLE
Prefill Fields in General Verification Form (airtable)

### ISSUE THREAD

**Issue by amandabee** [MuckRock/documentcloud-frontend#610]
Links to the DocumentCloud verification form (https://airtable.com/app93Yt5cwdVWTnqn/pagogIhgB1jZTzq00/form) should use the same "prefill" values as the Election Hub form, with one exception:   `MR User Display Name` can just be `MR User Name`

https://github.com/MuckRock/squarelet/issues/121

    MR User Name: Amanda Hickman
    MR Account URL: https://accounts.muckrock.com/users/amandabee/
    MR User Email: amanda@muckrock.com
    MR Organization Name: MuckRock Staff
    MR Organization Account URL: https://accounts.muckrock.com/organizations/muckrock/

https://airtable.com/app93Yt5cwdVWTnqn/pagogIhgB1jZTzq00/form?prefill_MR+User+Email=XXX&prefill_MR+User+Name=XXX&prefill_MR+User+Account+URL=XXX&prefill_MR+Organization+Name=XXX&prefill_MR+Organization+Account+URL=XXX

**Comment by duckduckgrayduck** [comment]
The manager is missing the ability to pull up the email address:
https://github.com/MuckRock/documentcloud-frontend/blob/master/src/manager/orgsAndUsers.js
All of the other fields should be able to be pulled to pre-populate the URL in https://github.com/MuckRock/documentcloud-frontend/blob/master/src/pages/app/Documents.svelte

**Comment by duckduckgrayduck** [comment]
I've added the ability to retrieve your own email in the DocumentCloud API by accessing /users/me in [this pull request](https://github.com/MuckRock/documentcloud/pull/237) which was a prerequisite to complete this task fully. Tomorrow I'll wrap up in #613

**Comment by amandabee** [comment]
This is quite thrilling.

However: it is pulling the user's Individual organization. For example: Gaetan Gras wants is requesting verification for IHECS. They created an organization (https://accounts.muckrock.com/organizations/ihecs/) but what I'm seeing in their [verification request](https://muckrock.zendesk.com/agent/tickets/131632) is: 

*  https://accounts.muckrock.com/organizations/gaetangras

(You'll see that there's a separate issue where Zapier is duplicating the beginning of the URL. I've already corrected that.)

**Comment by duckduckgrayduck** [comment]
The reason for this is when the user creates the organization their active organization on DocumentCloud is not changed. You'll see if the user changes their active organization the URL also changes. This should be a different feature request, as it is a site wide behavior that pre-dated the PR and touches different code.
