### ISSUE TITLE
Option to omit examples of pages matching the query from search results

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-frontend#639]
Relevant zendesk ticket:
https://muckrock.zendesk.com/agent/tickets/132673
"Is there an option to omit the “m of n pages matching the query” that appears under the main document link returned by a query?"

Could maybe up performance of queries too?

**Comment by eyeseast** [comment]
Can someone post an example URL?

**Comment by duckduckgrayduck** [comment]
https://www.documentcloud.org/app?q=Case%201%3A21-cv-00400-APM
