### ISSUE TITLE
Toolbars overflow on small screens

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#644]
Seeing this in both the top nav and the bottom toolbar. We may need to decide which things to hide when we run out of space.

![Screenshot 2024-08-28 at 8 48 12 AM](https://github.com/user-attachments/assets/c77879c1-4bbc-478a-9759-cc9db3eed0d9)

![Screenshot 2024-08-28 at 8 48 03 AM](https://github.com/user-attachments/assets/6466d66c-3d3e-4d86-9fbf-0d45dc58746f)

**Comment by allanlasser** [comment]
Yeah, we need some major design consideration for adapting to smaller screens.
