### ISSUE TITLE
"Edit Selected" button dialogue appears out of view in Safari

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#659]
![Image](https://github.com/user-attachments/assets/9ff4ebb7-ecd7-4a31-8ceb-346ae66a670d)

Safari Version 16.4 (18615.1.26.11.22)

When I select some documents and click "Edit Selected", the dialogue appears partially obscured. Happens on every breakpoint.

**Comment by allanlasser** [comment]
Closed in #683
