### ISSUE TITLE
Should document thumbnails have a max height?

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#669]
Thanks, Felt:

![Screenshot 2024-09-17 at 1 10 47 PM](https://github.com/user-attachments/assets/6fd05ced-c426-4567-ab3f-afd3dce9632f)

**Comment by allanlasser** [comment]
How about wrapping thumbnails in a container that fades them out if they're taller than it? [An effect like this](https://pqina.nl/blog/fade-out-overflow-using-css-mask-image/) but hiding, instead of scrolling, the overflow.

**Comment by eyeseast** [comment]
I like that. Seems worth trying.

**Comment by allanlasser** [comment]
Can you provide the image URL or thumbnail file here? Would be helpful for creating a Storybook.

**Comment by eyeseast** [comment]
This is the one in the screenshot: [Learn How To Do Isochrones In A Minute.pdf](https://github.com/user-attachments/files/17101212/Learn.How.To.Do.Isochrones.In.A.Minute.pdf)
