### ISSUE TITLE
Constrain note editing form to viewer width

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#689]
![Screenshot 2024-09-20 at 11 20 54 AM](https://github.com/user-attachments/assets/c291e405-7ffe-4f5b-af0c-21ef25f6eca9)

I made this use the page width, but really we want the viewer width. Ran into this because I needed to zoom to 200% to read this tiny text, so the page was wider than the viewer.

**Comment by eyeseast** [comment]
Related: I can't scroll down to see the full form if I'm adding a note at the bottom of the last page.

![Screenshot 2024-09-20 at 11 31 32 AM](https://github.com/user-attachments/assets/400388cc-9e31-4e0e-8e8c-7fdd26250265)

**Comment by allanlasser** [comment]
The width issue has been fixed by #777, but the issue with a note at the bottom of the viewport persists. Working on a fix for that.

**Comment by eyeseast** [comment]
We could probably use `floating-ui` to position the form above the highlight if we're at the bottom of the document.
