### ISSUE TITLE
Unclear what happens after clicking Begin upload

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-frontend#731]
When I click "Begin upload" on a document, it isn't clear to me that the document is actually being uploaded or that it has begun processing. It doesn't redirect me to the previous view (documents) nor give me any status bar to view that the document is in the process of uploading. 
![Upload](https://github.com/user-attachments/assets/6eb19a31-0189-4a82-873f-31eca59725f6)
Clicking "All documents" on the sidebar after finally shows me that a document is potentially being uploaded, but still no progress bar, just shows "0 pages" 
![0Pages](https://github.com/user-attachments/assets/9a616d19-a256-4821-8f8e-d73274655688)

**Comment by duckduckgrayduck** [comment]
I wonder if this is just a problem with my document? It seems to fail to upload the document/stuck in processing forever

**Comment by eyeseast** [comment]
This was a CORS issue. Uploads should work now. I'm going to open a separate issue on refactoring the upload UI.
