### ISSUE TITLE
Russian and Ukrainian are bolded in the language switcher, the rest are not

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-frontend#733]
![8-Language Switch Dropdown menu](https://github.com/user-attachments/assets/514d1f82-d513-4d13-9954-ad7b81c2c42c)

**Comment by allanlasser** [comment]
I don't think we're loading Cyrillic character sets, so this is falling back to browser/OS defaults. It seems suboptimal to load the entire Cyrillic font unless the user is actively browsing in Russian/Ukranian (and vice versa for Roman characters and Latin languages).

**Comment by eyeseast** [comment]
Short term solution: Write "Ukrainian" and "Russian" in English.
