### ISSUE TITLE
Adding a user sets all users to the same access

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#741]
[Feedback](https://baserow.io/database/128523/table/332915/575722/row/102) from @eyeseast 

This needs more detail: where does this happen?

**Comment by eyeseast** [comment]
It looks like changing any user's access will set the others to `view`, at least momentarily. Some mismatch in form values or hydration or something.

**Comment by eyeseast** [comment]
I wonder if this form would work better as client-only, similar to how we add and remove documents from a project. We don't need to update every user at once, and even on the server, we're updating one at a time.
