### ISSUE TITLE
Helpful metadata is missing from document list items

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#790]
[Feedback](https://baserow.io/database/128523/table/332915/575722/row/232):

> I really miss the project and tag/keyval listed with the files. even if just file belongs to a project or not would be useful information. I like how it is faster and more slicker, Thank you!

<img width="2017" alt="Screenshot 2024-10-25 at 10 01 29 AM" src="https://github.com/user-attachments/assets/c08b001c-bc97-4f48-a898-72d91677f193">

We've got lots of whitespace on the right side and the last line list items to restore a display of   metadata. We can prioritize Projects and Tags, with a limit of 5 items and an indicator if there's more to show.

**Comment by eyeseast** [comment]
> We've got lots of whitespace on the right side and the last line list items to restore a display of metadata. We can prioritize Projects and Tags, with a limit of 5 items and an indicator if there's more to show.

I think this is a good place to put all of that, with the caveat that it might need to disappear or collapse on mobile.
