### ISSUE TITLE
Translation strings showing

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud-frontend#818]
Clicking refresh on the upload page sometimes shows the translation keys instead of the proper translated strings:

![image](https://github.com/user-attachments/assets/3e94f257-26c4-47f0-a7eb-bdc87a286a72)

**Comment by mitchelljkotler** [comment]
Also happening for me on add-on search:
![image](https://github.com/user-attachments/assets/f2e0762d-c2ec-4702-9aeb-96bc270d31a2)

**Comment by eyeseast** [comment]
I can't reproduce this on uploads or the add-on list.

**Comment by eyeseast** [comment]
Closing this based on #868 but please reopen if you see this again.
