### ISSUE TITLE
AddOn run button

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud-frontend#821]
The Run... link and Add On Explore link both go to the same spot and are very close to each other in the main UI - this is confusing and seems redundant

**Comment by allanlasser** [comment]
The original design intention was to provide an add-on launcher from the "Run…" command, but it was cut for simplicity. We can remove run from the list. I would group this with #820 into a single PR that cleans up actions in the DocumentBrowser.
