### ISSUE TITLE
SvelteKit DocumentCloud Menu and Page Consistency

### ISSUE THREAD

**Issue by morisy** [MuckRock/documentcloud-frontend#840]
We'd like to have more consistency on DocumentCloud menu items. Some concepts underlying the redesign were (please correct or clarify as needed, couldn't find this explicit in the [Figma](https://www.figma.com/design/KVRuo8Ss3TvzreCmT6HQke/DC-SvelteKit?node-id=54-2&node-type=canvas&t=Vj6mitzg0QBdQeS2-0)):

* Users use the left bar for navigation.
* The right bar for action.

Right now, /documents/ /projects/ and /add-ons/ all off slight visual distinctions and different menu mappings, which I think hurts the usability more than we need to.

## Consistent Action Buttons

We should have a consistent ordering and appearance (when applicable) in the "Upload Documents" section in the top right and generally on the left rail so that if a user is used to looking there for some item, it will appear there.

![Image](https://github.com/user-attachments/assets/c64f194d-a10c-42da-9f69-eb3603c8d6e2)
![Image](https://github.com/user-attachments/assets/1041c3f3-f5a2-4b32-a93a-49ea224683d9)

For the `Upload Documents` action box, I'd suggest the following actions, with the asterisked actions only appearing on /projects/ pages:

*Upload* (or *Upload to Project*)

* Share & Embed (Make name consistent)
* Edit Metadata
* Edit Project Data*
* Edit Tags & Data
* Move to Project
* Reprocess
* Delete Document(s)
* Delete Project*
* View in Document Search*(would we still need this? Maybe we can drop it entirely?)

We should similarly keep the left hand side consistent, though adding `Project Collaborators` when on a project page but otherwise keeping the left hand menu the same.

I would suggest keeping that left hand rail for /add-on/ pages as well, and moving the Add-On pane to replace the right rail to be consistent with the initially stated left/right navigation/action distinction, while providing clearer markers for people to get back to the key area they're most likely to be interested in. I would also have the Add-Ons that don't run on documents still show the document pane for consistencies sake.

We should also be consistent in how items are capitalized. [Our current style guide](https://www.muckrock.com/style/) calls for clickable menu items to be capitalized; descriptive text should not be capitalized "Your Documents" button vs. "Your documents are safely saved." dialog. We have a place places such as `Edit Metadata` and `Move to project` in the `Upload Documents` dialogue area and `EXPLORE` by the `Projects` and `Add-Ons` menus where this convention is not followed.

**Comment by allanlasser** [comment]
@morisy I've noticed some similarity in how we show search shortcuts and how GitHub shows shortcuts for filtering issues:

![screenshot_2024-11-21_at_11 32 44___am_720](https://github.com/user-attachments/assets/82a8fcb6-4093-44e0-afef-4edac24aaa80)

If we moved the document search filtering shortcuts out of the left sidebar and into a search filter dropdown, this would go further to making the left sidebar globally consistent:

<img width="716" alt="Screenshot 2024-11-21 at 11 53 17 AM" src="https://github.com/user-attachments/assets/c044a301-82a8-4925-9eeb-2058511f1d10">

Thoughts?

**Comment by allanlasser** [comment]
I've forked this into three smaller issues with tighter scopes.
