### ISSUE TITLE
Add ability to expand/collapse all search highlights

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-frontend#865]
After #848, we're defaulting to showing search highlights by default, which can lead to highlights taking over the page. The old site shows the first three and allows you to show all (which adds state and complexity). 

I propose we add a top-level toggle that expands or collapses all highlights in one action, similar to selecting all documents.

**Comment by allanlasser** [comment]
Top level toggle in ResultsList would work well, since we can pass in an `open` prop to the PageHighlight and NoteHighlight. [Source](https://github.com/MuckRock/documentcloud-frontend/blob/dd651abe04c46443aefcda16e9096aef319cfea8/src/lib/components/documents/ResultsList.svelte#L122-L129)

**Comment by allanlasser** [comment]
Two approaches to providing the controls:

<img width="1245" alt="Screenshot 2024-11-21 at 12 06 06 PM" src="https://github.com/user-attachments/assets/0afd5f14-187f-48e7-be4d-d7e73ec22158">

1. Show a dropdown menu when there's an active search with actions
2. In each group, show the "All" actions
