### ISSUE TITLE
Consistent actions between document and project layouts

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#869]
[Feedback](https://baserow.io/database/128523/table/332915/575722/row/272):

> It's a bit challenging to find the projects that have been shared with me, have to remember where to click each time. New version looking great, btw!

---

Fork of #840 

Users are perceiving sidebars as application level UI, not view-specific UI, and changes to the sidebars disorient them.

We should have a consistent ordering, labelling, and positioning for elements in each sidebar on in Document, Project, and Add-On layouts. In other words, if a user is used to finding an action in a particular place, it should appear there.

We should be mindful that these sidebars are either appearing in the presence of a selectable list of documents, or in the presence of a document viewer. Sidebars aren't currently present when dispatching add-ons.

## Actions Sidebar

The right-hand sidebar should provide groups of actions that are consistently placed in the presence of a document browser or document viewer.

Proposed order:

1. Upload Documents
1. Document Actions
    1. Share & Embed (Make name consistent)
    1. Edit Metadata
    1. Edit Tags & Data
    1. Edit Projects
    1. Reprocess
    1. Delete
1. Project Actions (when on a project)
    1. Share & Embed Project
    1. Edit Project Data
    1. Delete Project
    1. Collaborators (Group)

## Navigation Sidebar

The left-hand sidebar should be globally consistent between documents, projects, and add-on routes. Each one should be a collapsable group, with a link to the top-level browser.

Proposed Order:

1. Documents (Explore Public Documents)
   1. Your Documents
   1. Your Public Documents
   1. Your Private Documents
   1. Org's Documents
   1. Pinned Documents…
1. Projects (Explore Public Projects)
   1. Your Projects
   1. Shared With You
   1. Pinned Projects…
1. Add-Ons
   1. Featured
   1. Pinned Add-Ons…

**Comment by allanlasser** [comment]
@morisy I want to flag a complication I encountered while working this. If we are moving towards a globally-consistent left sidebar, then users will lose this dependable navigation in the viewer. The viewer uses the left sidebar to present  document-specific links (its projects, tags and notes). This was one of the reasons I thought a Figma pass might be useful here—these changes could have large impacts on several different page designs and it'd be good to be able to consider them "in whole".

**Comment by eyeseast** [comment]
We might prioritize adjusting language first and layouts second. The language changes here are pretty straightforward. 

We can also standardize the search and project layouts without changing the viewer.

**Comment by allanlasser** [comment]
Yeah, I've decided to not touch the viewer in this pass and see if the changing sidebar still confuses people—then we can solve in a more targeted way.
