### ISSUE TITLE
Adjust layout of Add-Ons Dispatch page

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#870]
Fork of #840 

- Apply a globally-consistent left-sidebar from #869.
- Move the list of documents to the second column.
- Move the dispatch pane the right half for consistency with our actions-on-the-right pattern, while providing clearer wayfinding for users to return to another area.

Michael would also have the Add-Ons that don't run on documents still show the document pane for consistencies sake. I'm less in agreement here—if an add-on doesn't operate on documents, it's confusing to show a document list.

**Comment by eyeseast** [comment]
> Michael would also have the Add-Ons that don't run on documents still show the document pane for consistencies sake. I'm less in agreement here—if an add-on doesn't operate on documents, it's confusing to show a document list.

Strong agreement here. I think it's an anti-pattern to show a list of documents for add-ons that don't run on documents.
