### ISSUE TITLE
Set maximum height and overflow-scroll on Org List

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/documentcloud-frontend#872]
[Feedback](https://baserow.io/database/128523/table/332915/575722/row/363) from @morisy:

> If you are a member of a larger number of organizations (very rare edge case), it can be impossible to see all of the organizations you can switch to at certain screen sizes. 
>
> https://imgur.com/a/XPiukww

---

This should be a pure CSS fix by setting a maximum height on `OrgMenu` switcher and apply overflow scrolling.

**Comment by eyeseast** [comment]
I keep wondering if we should rethink this whole menu. It's a lot of stuff -- both UI and API requests -- hidden behind two layers of menu. I don't have a good answer on where it should go. Maybe its own page. Maybe over to Squarelet. Maybe this gets rethought as we roll out more ways for people to buy credits and such.

**Comment by allanlasser** [comment]
> I keep wondering if we should rethink this whole menu. It's a lot of stuff -- both UI and API requests -- hidden behind two layers of menu. 

I think you're right about it being too hidden. This was inherited from the design decisions of legacy without further reconsideration.

> I don't have a good answer on where it should go. Maybe its own page. Maybe over to Squarelet. Maybe this gets rethought as we roll out more ways for people to buy credits and such.

We'll still use the interactions: switching your active org and checking your credit balance, and having these accessible from any page are good. The member list offers a shortcut to see a specific user's docs, but that could be rolled into a "dashboard" page at the (unused) root route.
