### ISSUE TITLE
Pin the top toolbar?

### ISSUE THREAD

**Issue by mitchelljkotler** [MuckRock/documentcloud-frontend#886]
From Sam at Unredacted:

> Is it possible to ‘pin’ the top toolbar to the top of the frame, rather than having it floating? It currently feels slightly odd to have it over the top of the document text, with a small portion of the document peeking out at the top.

![Image](https://github.com/user-attachments/assets/b0fb46b8-437f-4e2c-9b48-594a1d6c0cfa)

**Comment by allanlasser** [comment]
It's good to acknowledge the feedback, but this is a aesthetic decision we've made for the viewer in the context of the site's overall design language and usability. If we change that decision, it'll have to be in response to usability issues or overwhelming user feedback.
