### ISSUE TITLE
DocumentCloud search interface missing element at certain breakpoints

### ISSUE THREAD

**Issue by morisy** [MuckRock/documentcloud-frontend#931]
At certain breakpoints, when the menu that displays "File", "Text', "Pages", and "Notes" becomes a dropdown, if a user searches that dropdown switches to "Undefined". Presumably that should instead indicate "Search":

![Image](https://github.com/user-attachments/assets/ed4ca99f-a8d3-4190-b707-13d0317d6ff4)

**Comment by eyeseast** [comment]
Fixed this on #930 too
