### ISSUE TITLE
Search-derived URLs don't work if shared

### ISSUE THREAD

**Issue by morisy** [MuckRock/documentcloud-frontend#932]
It looks like search is generating some non-functional URLs currently.

If you go to the Mueller Report, and do a search for Trump:

https://www.documentcloud.org/documents/5955118-The-Mueller-Report/?q=trump&mode=search

Pick page 31 result. That takes you to the expected page, and generates this URL:

https://www.documentcloud.org/documents/5955118-The-Mueller-Report/?mode=document&q=trump#document/p31

But if you paste that URL directly into a blank tab, it takes you to the first page of the document, not the 31st page.

**Comment by eyeseast** [comment]
This is fixed on #930
