### ISSUE TITLE
Crash viewer on large document

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-frontend#959]
I sorted docs by page count and selected one of the largest ones I could find (at 30k pages), and I first get a browser warning that it takes a long time, followed by a 502 bad gateway. 

https://www.documentcloud.org/documents/4480892-Circle-K-Family-Farms-EAW-Technical-Team-Initial/?mode=grid

**Comment by duckduckgrayduck** [comment]
Related: #844

**Comment by eyeseast** [comment]
Lambda has a limit on page size, and giant documents sometimes make us exceed that when we SSR. We fixed that in document and text mode but not grid https://www.documentcloud.org/documents/4480892-Circle-K-Family-Farms-EAW-Technical-Team-Initial/?mode=text

**Comment by eyeseast** [comment]
Looking at the actual document https://s3.documentcloud.org/documents/4480892/Circle-K-Family-Farms-EAW-Technical-Team-Initial.pdf it's mostly junk. Not sure if that's noteworthy.

**Comment by duckduckgrayduck** [comment]
Yea looks like you're right. Here is one from a gateway grant project:
https://www.documentcloud.org/documents/23465267-mta0mze2mg-compressed/
